In [2]:
import tensorflow as tf
print(tf.test.is_gpu_available())
print(tf.test.is_built_with_cuda())

True
True


In [1]:
import torch 
torch.cuda.is_available()

True

In [4]:
import torch
import numpy as np

### 1 张量初始化

In [18]:
#直接生成张量
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data.type)

#通过numpy数组生成张量
array = np.array(data)
x = torch.from_numpy(array)
print(x)

#通过已有的张量生成新的张量
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data,dtype= torch.float)
print(x_rand)

#指定数据维度来生成张量
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

<built-in method type of Tensor object at 0x7fb7cf524730>
tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.8504, 0.3657],
        [0.3823, 0.9341]])
Random Tensor: 
 tensor([[0.9681, 0.3122, 0.3901],
        [0.0990, 0.3479, 0.8742]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 2 张量属性

In [21]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 3 张量运算

In [32]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

#张量的索引和切片
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

#张量拼接
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

#矩阵的乘法
print(tensor.mul(tensor))
print(tensor*tensor)
#矩阵运算
print(f"tensor @ tensor.T: \n {tensor @ tensor.T}")

#自动赋值运算
tensor.add(5)
#tensor.add_(5) #自动赋值运算，会改变tensor原本的值
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor @ tensor.T: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 4 tensor与numpy的转化

In [37]:
#张量变换为Numpy array数组
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

#Numpy array数组转化为张量
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
